<?php

namespace SamuelMwangiW\Africastalking\Saloon\Requests;

use Sammyjo20\Saloon\Constants\Saloon;
use Sammyjo20\Saloon\Http\SaloonRequest;
use SamuelMwangiW\Africastalking\Enum\Service;
use SamuelMwangiW\Africastalking\Saloon\AfricastalkingConnector;

/**
 * @mixin AfricastalkingConnector
 */

abstract class BaseRequest extends SaloonRequest
{
    public Service $service;
    protected ?string $method = Saloon::POST;
    protected ?string $connector = AfricastalkingConnector::class;

    public function boot(BaseRequest|SaloonRequest $request): void
    {
        if ($request instanceof BaseRequest) {
            $request->service($this->service);
        }

        $request->addData('username', $this->username());

        parent::boot($request); // TODO: Change the autogenerated stub
    }
}
